server:
  port: 8088
  servlet:
    context-path: /

spring:
  application:
    name: demo-spring
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.own.spring.demo: debug

test:
  config-name: "Just a config"






