management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

logging:
  level:
    root: info
    org.apache: info
    org.springframework.web: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    com.alibaba.nacos: warn
    org.web3j: info
